name: fluuter_bloc_state_management_example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  cupertino_icons: ^1.0.5
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  very_good_analysis: ^3.1.0
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true